services:
  kocotree-skills-auth:
    image: kocotree-skills-auth:1.0
    container_name: kocotree-skills-auth
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    restart: on-failure
    networks:
      - kocotree-skills

networks:
  kocotree-skills:
    external: true
